version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "8000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend-abacate
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
